name: journey
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.13.1
  image_picker: ^0.8.4+8
  firebase_storage: ^11.7.7
  fluttertoast: ^8.2.6
  path_provider: ^2.0.9
  intl: ^0.17.0
  shared_preferences: ^2.0.10
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  assets:
    - assets/
  uses-material-design: true